// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ActionCooldown
    {
        [DataMember(Name = "timestamp")]
        public ulong Timestamp;
        [DataMember(Name = "cooldown")]
        public float Cooldown;

        public ActionCooldown(
            ulong Timestamp,
            float Cooldown
        )
        {
            this.Timestamp = Timestamp;
            this.Cooldown = Cooldown;
        }

        public ActionCooldown()
        {
        }
    }
}
