// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    public partial record ActionLogData : SpacetimeDB.TaggedEnum<(
        ActionLogDataSpaceAllocator Reserved,
        ItemStack WithdrawItem,
        ItemStack DepositItem
    )>;
}
