// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ActionState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "owner_entity_id")]
        public ulong OwnerEntityId;
        [DataMember(Name = "action_id")]
        public int ActionId;
        [DataMember(Name = "cooldown")]
        public ActionCooldown Cooldown;

        public ActionState(
            ulong EntityId,
            ulong OwnerEntityId,
            int ActionId,
            ActionCooldown Cooldown
        )
        {
            this.EntityId = EntityId;
            this.OwnerEntityId = OwnerEntityId;
            this.ActionId = ActionId;
            this.Cooldown = Cooldown;
        }

        public ActionState()
        {
            this.Cooldown = new();
        }
    }
}
