// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AutoClaimState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "owner_entity_id")]
        public ulong OwnerEntityId;

        public AutoClaimState(
            ulong EntityId,
            ulong OwnerEntityId
        )
        {
            this.EntityId = EntityId;
            this.OwnerEntityId = OwnerEntityId;
        }

        public AutoClaimState()
        {
        }
    }
}
