// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BarterStallSetMarketModeEnabledRequest
    {
        [DataMember(Name = "shop_entity_id")]
        public ulong ShopEntityId;
        [DataMember(Name = "enabled")]
        public bool Enabled;

        public BarterStallSetMarketModeEnabledRequest(
            ulong ShopEntityId,
            bool Enabled
        )
        {
            this.ShopEntityId = ShopEntityId;
            this.Enabled = Enabled;
        }

        public BarterStallSetMarketModeEnabledRequest()
        {
        }
    }
}
