// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BuildingNicknameState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "nickname")]
        public string Nickname;

        public BuildingNicknameState(
            ulong EntityId,
            string Nickname
        )
        {
            this.EntityId = EntityId;
            this.Nickname = Nickname;
        }

        public BuildingNicknameState()
        {
            this.Nickname = "";
        }
    }
}
