// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CappedLevelRequirement
    {
        [DataMember(Name = "skill_id")]
        public int SkillId;
        [DataMember(Name = "min_level")]
        public int MinLevel;
        [DataMember(Name = "max_level")]
        public int MaxLevel;

        public CappedLevelRequirement(
            int SkillId,
            int MinLevel,
            int MaxLevel
        )
        {
            this.SkillId = SkillId;
            this.MinLevel = MinLevel;
            this.MaxLevel = MaxLevel;
        }

        public CappedLevelRequirement()
        {
        }
    }
}
