// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ClaimSetPurchaseSupplyPriceRequest
    {
        [DataMember(Name = "building_entity_id")]
        public ulong BuildingEntityId;
        [DataMember(Name = "purchase_price")]
        public float PurchasePrice;

        public ClaimSetPurchaseSupplyPriceRequest(
            ulong BuildingEntityId,
            float PurchasePrice
        )
        {
            this.BuildingEntityId = BuildingEntityId;
            this.PurchasePrice = PurchasePrice;
        }

        public ClaimSetPurchaseSupplyPriceRequest()
        {
        }
    }
}
