// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Config
    {
        [DataMember(Name = "version")]
        public int Version;
        [DataMember(Name = "env")]
        public string Env;
        [DataMember(Name = "agents_enabled")]
        public bool AgentsEnabled;

        public Config(
            int Version,
            string Env,
            bool AgentsEnabled
        )
        {
            this.Version = Version;
            this.Env = Env;
            this.AgentsEnabled = AgentsEnabled;
        }

        public Config()
        {
            this.Env = "";
        }
    }
}
