// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ContributionLootDesc
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "enemy_type_id")]
        public int EnemyTypeId;
        [DataMember(Name = "item_list_id")]
        public int ItemListId;
        [DataMember(Name = "minimum_contribution")]
        public int MinimumContribution;

        public ContributionLootDesc(
            int Id,
            int EnemyTypeId,
            int ItemListId,
            int MinimumContribution
        )
        {
            this.Id = Id;
            this.EnemyTypeId = EnemyTypeId;
            this.ItemListId = ItemListId;
            this.MinimumContribution = MinimumContribution;
        }

        public ContributionLootDesc()
        {
        }
    }
}
