// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EmpireState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "capital_building_entity_id")]
        public ulong CapitalBuildingEntityId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "shard_treasury")]
        public uint ShardTreasury;
        [DataMember(Name = "nobility_threshold")]
        public int NobilityThreshold;
        [DataMember(Name = "num_claims")]
        public int NumClaims;
        [DataMember(Name = "location")]
        public OffsetCoordinatesSmallMessage Location;

        public EmpireState(
            ulong EntityId,
            ulong CapitalBuildingEntityId,
            string Name,
            uint ShardTreasury,
            int NobilityThreshold,
            int NumClaims,
            OffsetCoordinatesSmallMessage Location
        )
        {
            this.EntityId = EntityId;
            this.CapitalBuildingEntityId = CapitalBuildingEntityId;
            this.Name = Name;
            this.ShardTreasury = ShardTreasury;
            this.NobilityThreshold = NobilityThreshold;
            this.NumClaims = NumClaims;
            this.Location = Location;
        }

        public EmpireState()
        {
            this.Name = "";
            this.Location = new();
        }
    }
}
