// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EmpirePlayerDataState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "empire_entity_id")]
        public ulong EmpireEntityId;
        [DataMember(Name = "rank")]
        public byte Rank;
        [DataMember(Name = "donated_shards")]
        public uint DonatedShards;
        [DataMember(Name = "noble")]
        public SpacetimeDB.Timestamp? Noble;

        public EmpirePlayerDataState(
            ulong EntityId,
            ulong EmpireEntityId,
            byte Rank,
            uint DonatedShards,
            SpacetimeDB.Timestamp? Noble
        )
        {
            this.EntityId = EntityId;
            this.EmpireEntityId = EmpireEntityId;
            this.Rank = Rank;
            this.DonatedShards = DonatedShards;
            this.Noble = Noble;
        }

        public EmpirePlayerDataState()
        {
        }
    }
}
