// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    public enum EmpireNotificationType
    {
        None,
        NewMember,
        MarkedForSiege,
        StartedSiege,
        StartedDefense,
        SuccessfulSiege,
        SuccessfulDefense,
        FailedSiege,
        FailedDefense,
        MemberLeft,
        WatchtowerBuilt,
        ClaimJoined,
        ClaimLeft,
        Donation,
        DonationByProxy,
    }
}
