// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    public enum EnemyType
    {
        None,
        PracticeDummy,
        GrassBird,
        DesertBird,
        SwampBird,
        Goat,
        MountainGoat,
        DeerFemale,
        DeerMale,
        Elk,
        BoarFemale,
        BoarMale,
        BoarElder,
        PlainsOx,
        TundraOx,
        JungleLargeBird,
        DesertLargeBird,
        Jakyl,
        AlphaJakyl,
        KingJakyl,
        RockCrab,
        DesertCrab,
        FrostCrab,
        ForestToad,
        SwampToad,
        FrostToad,
        Umbura,
        AlphaUmbura,
        KingUmbura,
        Drone,
        Soldier,
        Queen,
        Sentinel,
        SentinelDungeonJakyl,
        SentinelDungeonSkitch,
        SentinelDungeonLargeJakyl,
    }
}
