// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ExperienceStack
    {
        [DataMember(Name = "skill_id")]
        public int SkillId;
        [DataMember(Name = "quantity")]
        public int Quantity;

        public ExperienceStack(
            int SkillId,
            int Quantity
        )
        {
            this.SkillId = SkillId;
            this.Quantity = Quantity;
        }

        public ExperienceStack()
        {
        }
    }
}
