// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ExplorationChunksState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "bitmap")]
        public System.Collections.Generic.List<ulong> Bitmap;
        [DataMember(Name = "explored_chunks_count")]
        public int ExploredChunksCount;

        public ExplorationChunksState(
            ulong EntityId,
            System.Collections.Generic.List<ulong> Bitmap,
            int ExploredChunksCount
        )
        {
            this.EntityId = EntityId;
            this.Bitmap = Bitmap;
            this.ExploredChunksCount = ExploredChunksCount;
        }

        public ExplorationChunksState()
        {
            this.Bitmap = new();
        }
    }
}
