// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class HerdState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "enemy_ai_params_desc_id")]
        public int EnemyAiParamsDescId;
        [DataMember(Name = "current_population")]
        public int CurrentPopulation;
        [DataMember(Name = "ignore_eagerness")]
        public bool IgnoreEagerness;
        [DataMember(Name = "population_variance")]
        public System.Collections.Generic.List<float> PopulationVariance;

        public HerdState(
            ulong EntityId,
            int EnemyAiParamsDescId,
            int CurrentPopulation,
            bool IgnoreEagerness,
            System.Collections.Generic.List<float> PopulationVariance
        )
        {
            this.EntityId = EntityId;
            this.EnemyAiParamsDescId = EnemyAiParamsDescId;
            this.CurrentPopulation = CurrentPopulation;
            this.IgnoreEagerness = IgnoreEagerness;
            this.PopulationVariance = PopulationVariance;
        }

        public HerdState()
        {
            this.PopulationVariance = new();
        }
    }
}
