// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class KnowledgeEntry
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "state")]
        public KnowledgeState State;

        public KnowledgeEntry(
            int Id,
            KnowledgeState State
        )
        {
            this.Id = Id;
            this.State = State;
        }

        public KnowledgeEntry()
        {
        }
    }
}
