// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class OnRegionPlayerCreatedMsg
    {
        [DataMember(Name = "player_entity_id")]
        public ulong PlayerEntityId;

        public OnRegionPlayerCreatedMsg(ulong PlayerEntityId)
        {
            this.PlayerEntityId = PlayerEntityId;
        }

        public OnRegionPlayerCreatedMsg()
        {
        }
    }
}
