// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerClaimTransferOwnershipRequest
    {
        [DataMember(Name = "new_owner_entity_id")]
        public ulong NewOwnerEntityId;
        [DataMember(Name = "claim_entity_id")]
        public ulong ClaimEntityId;

        public PlayerClaimTransferOwnershipRequest(
            ulong NewOwnerEntityId,
            ulong ClaimEntityId
        )
        {
            this.NewOwnerEntityId = NewOwnerEntityId;
            this.ClaimEntityId = ClaimEntityId;
        }

        public PlayerClaimTransferOwnershipRequest()
        {
        }
    }
}
