// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerClosedListingCollectRequest
    {
        [DataMember(Name = "building_entity_id")]
        public ulong BuildingEntityId;
        [DataMember(Name = "auction_listing_entity_id")]
        public ulong AuctionListingEntityId;

        public PlayerClosedListingCollectRequest(
            ulong BuildingEntityId,
            ulong AuctionListingEntityId
        )
        {
            this.BuildingEntityId = BuildingEntityId;
            this.AuctionListingEntityId = AuctionListingEntityId;
        }

        public PlayerClosedListingCollectRequest()
        {
        }
    }
}
