// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit dev).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerCraftInitiateRequest
    {
        [DataMember(Name = "recipe_id")]
        public int RecipeId;
        [DataMember(Name = "building_entity_id")]
        public ulong BuildingEntityId;
        [DataMember(Name = "count")]
        public int Count;
        [DataMember(Name = "timestamp")]
        public ulong Timestamp;

        public PlayerCraftInitiateRequest(
            int RecipeId,
            ulong BuildingEntityId,
            int Count,
            ulong Timestamp
        )
        {
            this.RecipeId = RecipeId;
            this.BuildingEntityId = BuildingEntityId;
            this.Count = Count;
            this.Timestamp = Timestamp;
        }

        public PlayerCraftInitiateRequest()
        {
        }
    }
}
