// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerTradeInitiateSessionRequest
    {
        [DataMember(Name = "acceptor_entity_id")]
        public ulong AcceptorEntityId;

        public PlayerTradeInitiateSessionRequest(ulong AcceptorEntityId)
        {
            this.AcceptorEntityId = AcceptorEntityId;
        }

        public PlayerTradeInitiateSessionRequest()
        {
        }
    }
}
