// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerPortalEnterRequest
    {
        [DataMember(Name = "portal_entity_id")]
        public ulong PortalEntityId;

        public PlayerPortalEnterRequest(ulong PortalEntityId)
        {
            this.PortalEntityId = PortalEntityId;
        }

        public PlayerPortalEnterRequest()
        {
        }
    }
}
