// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerUsernameState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "username")]
        public string Username;

        public PlayerUsernameState(
            ulong EntityId,
            string Username
        )
        {
            this.EntityId = EntityId;
            this.Username = Username;
        }

        public PlayerUsernameState()
        {
            this.Username = "";
        }
    }
}
