// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerHousingRequestAccessRequest
    {
        [DataMember(Name = "building_entity_id")]
        public ulong BuildingEntityId;
        [DataMember(Name = "owner_entity_id")]
        public ulong OwnerEntityId;

        public PlayerHousingRequestAccessRequest(
            ulong BuildingEntityId,
            ulong OwnerEntityId
        )
        {
            this.BuildingEntityId = BuildingEntityId;
            this.OwnerEntityId = OwnerEntityId;
        }

        public PlayerHousingRequestAccessRequest()
        {
        }
    }
}
