// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerRetrieveLostItemRequest
    {
        [DataMember(Name = "building_entity_id")]
        public ulong BuildingEntityId;
        [DataMember(Name = "item_id")]
        public int ItemId;
        [DataMember(Name = "is_cargo")]
        public bool IsCargo;
        [DataMember(Name = "durability")]
        public int Durability;

        public PlayerRetrieveLostItemRequest(
            ulong BuildingEntityId,
            int ItemId,
            bool IsCargo,
            int Durability
        )
        {
            this.BuildingEntityId = BuildingEntityId;
            this.ItemId = ItemId;
            this.IsCargo = IsCargo;
            this.Durability = Durability;
        }

        public PlayerRetrieveLostItemRequest()
        {
        }
    }
}
