// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerSetDefaultDeployableRequest
    {
        [DataMember(Name = "deployable_collectible_id")]
        public int DeployableCollectibleId;

        public PlayerSetDefaultDeployableRequest(int DeployableCollectibleId)
        {
            this.DeployableCollectibleId = DeployableCollectibleId;
        }

        public PlayerSetDefaultDeployableRequest()
        {
        }
    }
}
