// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PocketKey
    {
        [DataMember(Name = "inventory_entity_id")]
        public ulong InventoryEntityId;
        [DataMember(Name = "pocket_index")]
        public int PocketIndex;

        public PocketKey(
            ulong InventoryEntityId,
            int PocketIndex
        )
        {
            this.InventoryEntityId = InventoryEntityId;
            this.PocketIndex = PocketIndex;
        }

        public PocketKey()
        {
        }
    }
}
