// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PrivateParametersDesc
    {
        [DataMember(Name = "version")]
        public int Version;
        [DataMember(Name = "move_validation")]
        public MoveValidationParamsDesc MoveValidation;

        public PrivateParametersDesc(
            int Version,
            MoveValidationParamsDesc MoveValidation
        )
        {
            this.Version = Version;
            this.MoveValidation = MoveValidation;
        }

        public PrivateParametersDesc()
        {
            this.MoveValidation = new();
        }
    }
}
