// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ServerIdentity
    {
        [DataMember(Name = "version")]
        public byte Version;
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;

        public ServerIdentity(
            byte Version,
            SpacetimeDB.Identity Identity
        )
        {
            this.Version = Version;
            this.Identity = Identity;
        }

        public ServerIdentity()
        {
        }
    }
}
