// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class StagedStaticDataV3
    {
        [DataMember(Name = "version")]
        public uint Version;
        [DataMember(Name = "static_data")]
        public StaticDataUploadV3 StaticData;

        public StagedStaticDataV3(
            uint Version,
            StaticDataUploadV3 StaticData
        )
        {
            this.Version = Version;
            this.StaticData = StaticData;
        }

        public StagedStaticDataV3()
        {
            this.StaticData = new();
        }
    }
}
