// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TargetState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "target_entity_id")]
        public ulong TargetEntityId;

        public TargetState(
            ulong EntityId,
            ulong TargetEntityId
        )
        {
            this.EntityId = EntityId;
            this.TargetEntityId = TargetEntityId;
        }

        public TargetState()
        {
        }
    }
}
