// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ThreatState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "owner_entity_id")]
        public ulong OwnerEntityId;
        [DataMember(Name = "target_entity_id")]
        public ulong TargetEntityId;
        [DataMember(Name = "threat")]
        public float Threat;

        public ThreatState(
            ulong EntityId,
            ulong OwnerEntityId,
            ulong TargetEntityId,
            float Threat
        )
        {
            this.EntityId = EntityId;
            this.OwnerEntityId = OwnerEntityId;
            this.TargetEntityId = TargetEntityId;
            this.Threat = Threat;
        }

        public ThreatState()
        {
        }
    }
}
