// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class UserUpdateRegionMsg
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "region_id")]
        public byte RegionId;

        public UserUpdateRegionMsg(
            SpacetimeDB.Identity Identity,
            byte RegionId
        )
        {
            this.Identity = Identity;
            this.RegionId = RegionId;
        }

        public UserUpdateRegionMsg()
        {
        }
    }
}
