// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class UserAuthenticationState
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "timestamp")]
        public SpacetimeDB.Timestamp Timestamp;

        public UserAuthenticationState(
            SpacetimeDB.Identity Identity,
            SpacetimeDB.Timestamp Timestamp
        )
        {
            this.Identity = Identity;
            this.Timestamp = Timestamp;
        }

        public UserAuthenticationState()
        {
        }
    }
}
