// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AdminRestorePlayerStateTimerHandle : RemoteTableHandle<EventContext, AdminRestorePlayerStateTimer>
        {
            protected override string RemoteTableName => "admin_restore_player_state_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(AdminRestorePlayerStateTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(AdminRestorePlayerStateTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal AdminRestorePlayerStateTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(AdminRestorePlayerStateTimer row) => row.ScheduledId;
        }

        public readonly AdminRestorePlayerStateTimerHandle AdminRestorePlayerStateTimer;
    }
}
