// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AdminBroadcastHandle : RemoteTableHandle<EventContext, AdminBroadcast>
        {
            protected override string RemoteTableName => "admin_broadcast";

            public sealed class VersionUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(AdminBroadcast row) => row.Version;

                public VersionUniqueIndex(AdminBroadcastHandle table) : base(table) { }
            }

            public readonly VersionUniqueIndex Version;

            internal AdminBroadcastHandle(DbConnection conn) : base(conn)
            {
                Version = new(this);
            }

            protected override object GetPrimaryKey(AdminBroadcast row) => row.Version;
        }

        public readonly AdminBroadcastHandle AdminBroadcast;
    }
}
