// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AdminClearResourceTimerHandle : RemoteTableHandle<EventContext, AdminClearResourceTimer>
        {
            protected override string RemoteTableName => "admin_clear_resource_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(AdminClearResourceTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(AdminClearResourceTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal AdminClearResourceTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(AdminClearResourceTimer row) => row.ScheduledId;
        }

        public readonly AdminClearResourceTimerHandle AdminClearResourceTimer;
    }
}
