// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AttackImpactTimerMigratedHandle : RemoteTableHandle<EventContext, AttackImpactTimerMigrated>
        {
            protected override string RemoteTableName => "attack_impact_timer_migrated";

            public sealed class AttackerEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(AttackImpactTimerMigrated row) => row.AttackerEntityId;

                public AttackerEntityIdIndex(AttackImpactTimerMigratedHandle table) : base(table) { }
            }

            public readonly AttackerEntityIdIndex AttackerEntityId;

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(AttackImpactTimerMigrated row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(AttackImpactTimerMigratedHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal AttackImpactTimerMigratedHandle(DbConnection conn) : base(conn)
            {
                AttackerEntityId = new(this);
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(AttackImpactTimerMigrated row) => row.ScheduledId;
        }

        public readonly AttackImpactTimerMigratedHandle AttackImpactTimerMigrated;
    }
}
