// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AutoLogoutLoopTimerHandle : RemoteTableHandle<EventContext, AutoLogoutLoopTimer>
        {
            protected override string RemoteTableName => "auto_logout_loop_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(AutoLogoutLoopTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(AutoLogoutLoopTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal AutoLogoutLoopTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(AutoLogoutLoopTimer row) => row.ScheduledId;
        }

        public readonly AutoLogoutLoopTimerHandle AutoLogoutLoopTimer;
    }
}
