// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BarterStallStateHandle : RemoteTableHandle<EventContext, BarterStallState>
        {
            protected override string RemoteTableName => "barter_stall_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(BarterStallState row) => row.EntityId;

                public EntityIdUniqueIndex(BarterStallStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal BarterStallStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(BarterStallState row) => row.EntityId;
        }

        public readonly BarterStallStateHandle BarterStallState;
    }
}
