// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit dev).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BuffDescHandle : RemoteTableHandle<EventContext, BuffDesc>
        {
            protected override string RemoteTableName => "buff_desc";

            public sealed class BuffTypeIdIndex : BTreeIndexBase<int>
            {
                protected override int GetKey(BuffDesc row) => row.BuffTypeId;

                public BuffTypeIdIndex(BuffDescHandle table) : base(table) { }
            }

            public readonly BuffTypeIdIndex BuffTypeId;

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(BuffDesc row) => row.Id;

                public IdUniqueIndex(BuffDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal BuffDescHandle(DbConnection conn) : base(conn)
            {
                BuffTypeId = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(BuffDesc row) => row.Id;
        }

        public readonly BuffDescHandle BuffDesc;
    }
}
