// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BuildingClaimDescHandle : RemoteTableHandle<EventContext, BuildingClaimDesc>
        {
            protected override string RemoteTableName => "building_claim_desc";

            public sealed class BuildingIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(BuildingClaimDesc row) => row.BuildingId;

                public BuildingIdUniqueIndex(BuildingClaimDescHandle table) : base(table) { }
            }

            public readonly BuildingIdUniqueIndex BuildingId;

            internal BuildingClaimDescHandle(DbConnection conn) : base(conn)
            {
                BuildingId = new(this);
            }

            protected override object GetPrimaryKey(BuildingClaimDesc row) => row.BuildingId;
        }

        public readonly BuildingClaimDescHandle BuildingClaimDesc;
    }
}
