// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BuildingTypeDescHandle : RemoteTableHandle<EventContext, BuildingTypeDesc>
        {
            protected override string RemoteTableName => "building_type_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(BuildingTypeDesc row) => row.Id;

                public IdUniqueIndex(BuildingTypeDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal BuildingTypeDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(BuildingTypeDesc row) => row.Id;
        }

        public readonly BuildingTypeDescHandle BuildingTypeDesc;
    }
}
