// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BuildingRepairsDescHandle : RemoteTableHandle<EventContext, BuildingRepairsDesc>
        {
            protected override string RemoteTableName => "building_repairs_desc";

            public sealed class CargoIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(BuildingRepairsDesc row) => row.CargoId;

                public CargoIdUniqueIndex(BuildingRepairsDescHandle table) : base(table) { }
            }

            public readonly CargoIdUniqueIndex CargoId;

            internal BuildingRepairsDescHandle(DbConnection conn) : base(conn)
            {
                CargoId = new(this);
            }

            protected override object GetPrimaryKey(BuildingRepairsDesc row) => row.CargoId;
        }

        public readonly BuildingRepairsDescHandle BuildingRepairsDesc;
    }
}
