// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BuildingSpawnDescHandle : RemoteTableHandle<EventContext, BuildingSpawnDesc>
        {
            protected override string RemoteTableName => "building_spawn_desc";

            public sealed class BuildingIdIndex : BTreeIndexBase<int>
            {
                protected override int GetKey(BuildingSpawnDesc row) => row.BuildingId;

                public BuildingIdIndex(BuildingSpawnDescHandle table) : base(table) { }
            }

            public readonly BuildingIdIndex BuildingId;

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(BuildingSpawnDesc row) => row.Id;

                public IdUniqueIndex(BuildingSpawnDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal BuildingSpawnDescHandle(DbConnection conn) : base(conn)
            {
                BuildingId = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(BuildingSpawnDesc row) => row.Id;
        }

        public readonly BuildingSpawnDescHandle BuildingSpawnDesc;
    }
}
