// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BuildingDespawnTimerHandle : RemoteTableHandle<EventContext, BuildingDespawnTimer>
        {
            protected override string RemoteTableName => "building_despawn_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(BuildingDespawnTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(BuildingDespawnTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal BuildingDespawnTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(BuildingDespawnTimer row) => row.ScheduledId;
        }

        public readonly BuildingDespawnTimerHandle BuildingDespawnTimer;
    }
}
