// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CargoDescHandle : RemoteTableHandle<EventContext, CargoDesc>
        {
            protected override string RemoteTableName => "cargo_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(CargoDesc row) => row.Id;

                public IdUniqueIndex(CargoDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal CargoDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(CargoDesc row) => row.Id;
        }

        public readonly CargoDescHandle CargoDesc;
    }
}
