// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CharacterStatDescHandle : RemoteTableHandle<EventContext, CharacterStatDesc>
        {
            protected override string RemoteTableName => "character_stat_desc";

            public sealed class StatTypeUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(CharacterStatDesc row) => row.StatType;

                public StatTypeUniqueIndex(CharacterStatDescHandle table) : base(table) { }
            }

            public readonly StatTypeUniqueIndex StatType;

            internal CharacterStatDescHandle(DbConnection conn) : base(conn)
            {
                StatType = new(this);
            }

            protected override object GetPrimaryKey(CharacterStatDesc row) => row.StatType;
        }

        public readonly CharacterStatDescHandle CharacterStatDesc;
    }
}
