// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CharacterStatsStateHandle : RemoteTableHandle<EventContext, CharacterStatsState>
        {
            protected override string RemoteTableName => "character_stats_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(CharacterStatsState row) => row.EntityId;

                public EntityIdUniqueIndex(CharacterStatsStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal CharacterStatsStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(CharacterStatsState row) => row.EntityId;
        }

        public readonly CharacterStatsStateHandle CharacterStatsState;
    }
}
