// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ChatCleanupTimerHandle : RemoteTableHandle<EventContext, ChatCleanupTimer>
        {
            protected override string RemoteTableName => "chat_cleanup_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ChatCleanupTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(ChatCleanupTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal ChatCleanupTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(ChatCleanupTimer row) => row.ScheduledId;
        }

        public readonly ChatCleanupTimerHandle ChatCleanupTimer;
    }
}
