// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ChestRarityDescHandle : RemoteTableHandle<EventContext, ChestRarityDesc>
        {
            protected override string RemoteTableName => "chest_rarity_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ChestRarityDesc row) => row.Id;

                public IdUniqueIndex(ChestRarityDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ChestRarityDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ChestRarityDesc row) => row.Id;
        }

        public readonly ChestRarityDescHandle ChestRarityDesc;
    }
}
