// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ClaimRecruitmentStateHandle : RemoteTableHandle<EventContext, ClaimRecruitmentState>
        {
            protected override string RemoteTableName => "claim_recruitment_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ClaimRecruitmentState row) => row.EntityId;

                public EntityIdUniqueIndex(ClaimRecruitmentStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal ClaimRecruitmentStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(ClaimRecruitmentState row) => row.EntityId;
        }

        public readonly ClaimRecruitmentStateHandle ClaimRecruitmentState;
    }
}
