// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ClaimTechUnlockTimerHandle : RemoteTableHandle<EventContext, ClaimTechUnlockTimer>
        {
            protected override string RemoteTableName => "claim_tech_unlock_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ClaimTechUnlockTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(ClaimTechUnlockTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal ClaimTechUnlockTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(ClaimTechUnlockTimer row) => row.ScheduledId;
        }

        public readonly ClaimTechUnlockTimerHandle ClaimTechUnlockTimer;
    }
}
