// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ClaimTileCostHandle : RemoteTableHandle<EventContext, ClaimTileCost>
        {
            protected override string RemoteTableName => "claim_tile_cost";

            public sealed class TileCountUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ClaimTileCost row) => row.TileCount;

                public TileCountUniqueIndex(ClaimTileCostHandle table) : base(table) { }
            }

            public readonly TileCountUniqueIndex TileCount;

            internal ClaimTileCostHandle(DbConnection conn) : base(conn)
            {
                TileCount = new(this);
            }

            protected override object GetPrimaryKey(ClaimTileCost row) => row.TileCount;
        }

        public readonly ClaimTileCostHandle ClaimTileCost;
    }
}
