// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CollectStatsTimerHandle : RemoteTableHandle<EventContext, CollectStatsTimer>
        {
            protected override string RemoteTableName => "collect_stats_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(CollectStatsTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(CollectStatsTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal CollectStatsTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(CollectStatsTimer row) => row.ScheduledId;
        }

        public readonly CollectStatsTimerHandle CollectStatsTimer;
    }
}
