// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CombatActionDescHandle : RemoteTableHandle<EventContext, CombatActionDesc>
        {
            protected override string RemoteTableName => "combat_action_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(CombatActionDesc row) => row.Id;

                public IdUniqueIndex(CombatActionDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class LearnedByPlayerIndex : BTreeIndexBase<bool>
            {
                protected override bool GetKey(CombatActionDesc row) => row.LearnedByPlayer;

                public LearnedByPlayerIndex(CombatActionDescHandle table) : base(table) { }
            }

            public readonly LearnedByPlayerIndex LearnedByPlayer;

            internal CombatActionDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                LearnedByPlayer = new(this);
            }

            protected override object GetPrimaryKey(CombatActionDesc row) => row.Id;
        }

        public readonly CombatActionDescHandle CombatActionDesc;
    }
}
