// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CombatStateHandle : RemoteTableHandle<EventContext, CombatState>
        {
            protected override string RemoteTableName => "combat_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(CombatState row) => row.EntityId;

                public EntityIdUniqueIndex(CombatStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal CombatStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(CombatState row) => row.EntityId;
        }

        public readonly CombatStateHandle CombatState;
    }
}
