// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CombatActionDescV2Handle : RemoteTableHandle<EventContext, CombatActionDescV2>
        {
            protected override string RemoteTableName => "combat_action_desc_v2";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(CombatActionDescV2 row) => row.Id;

                public IdUniqueIndex(CombatActionDescV2Handle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class LearnedByPlayerIndex : BTreeIndexBase<bool>
            {
                protected override bool GetKey(CombatActionDescV2 row) => row.LearnedByPlayer;

                public LearnedByPlayerIndex(CombatActionDescV2Handle table) : base(table) { }
            }

            public readonly LearnedByPlayerIndex LearnedByPlayer;

            internal CombatActionDescV2Handle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                LearnedByPlayer = new(this);
            }

            protected override object GetPrimaryKey(CombatActionDescV2 row) => row.Id;
        }

        public readonly CombatActionDescV2Handle CombatActionDescV2;
    }
}
