// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CraftingRecipeDescHandle : RemoteTableHandle<EventContext, CraftingRecipeDesc>
        {
            protected override string RemoteTableName => "crafting_recipe_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(CraftingRecipeDesc row) => row.Id;

                public IdUniqueIndex(CraftingRecipeDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal CraftingRecipeDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(CraftingRecipeDesc row) => row.Id;
        }

        public readonly CraftingRecipeDescHandle CraftingRecipeDesc;
    }
}
