// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DayNightLoopTimerHandle : RemoteTableHandle<EventContext, DayNightLoopTimer>
        {
            protected override string RemoteTableName => "day_night_loop_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(DayNightLoopTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(DayNightLoopTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal DayNightLoopTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(DayNightLoopTimer row) => row.ScheduledId;
        }

        public readonly DayNightLoopTimerHandle DayNightLoopTimer;
    }
}
