// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DeveloperHandle : RemoteTableHandle<EventContext, Developer>
        {
            protected override string RemoteTableName => "developer";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Developer row) => row.Identity;

                public IdentityUniqueIndex(DeveloperHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal DeveloperHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(Developer row) => row.Identity;
        }

        public readonly DeveloperHandle Developer;
    }
}
