// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DroppedInventoryStateHandle : RemoteTableHandle<EventContext, DroppedInventoryState>
        {
            protected override string RemoteTableName => "dropped_inventory_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(DroppedInventoryState row) => row.EntityId;

                public EntityIdUniqueIndex(DroppedInventoryStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class OwnerEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(DroppedInventoryState row) => row.OwnerEntityId;

                public OwnerEntityIdIndex(DroppedInventoryStateHandle table) : base(table) { }
            }

            public readonly OwnerEntityIdIndex OwnerEntityId;

            internal DroppedInventoryStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                OwnerEntityId = new(this);
            }

            protected override object GetPrimaryKey(DroppedInventoryState row) => row.EntityId;
        }

        public readonly DroppedInventoryStateHandle DroppedInventoryState;
    }
}
