// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DuelAgentTimerHandle : RemoteTableHandle<EventContext, DuelAgentTimer>
        {
            protected override string RemoteTableName => "duel_agent_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(DuelAgentTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(DuelAgentTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal DuelAgentTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(DuelAgentTimer row) => row.ScheduledId;
        }

        public readonly DuelAgentTimerHandle DuelAgentTimer;
    }
}
