// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EmpireRankDescHandle : RemoteTableHandle<EventContext, EmpireRankDesc>
        {
            protected override string RemoteTableName => "empire_rank_desc";

            public sealed class RankUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(EmpireRankDesc row) => row.Rank;

                public RankUniqueIndex(EmpireRankDescHandle table) : base(table) { }
            }

            public readonly RankUniqueIndex Rank;

            internal EmpireRankDescHandle(DbConnection conn) : base(conn)
            {
                Rank = new(this);
            }

            protected override object GetPrimaryKey(EmpireRankDesc row) => row.Rank;
        }

        public readonly EmpireRankDescHandle EmpireRankDesc;
    }
}
