// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EmpireTerritoryDescHandle : RemoteTableHandle<EventContext, EmpireTerritoryDesc>
        {
            protected override string RemoteTableName => "empire_territory_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(EmpireTerritoryDesc row) => row.Id;

                public IdUniqueIndex(EmpireTerritoryDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal EmpireTerritoryDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(EmpireTerritoryDesc row) => row.Id;
        }

        public readonly EmpireTerritoryDescHandle EmpireTerritoryDesc;
    }
}
