// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EmpireIconDescHandle : RemoteTableHandle<EventContext, EmpireIconDesc>
        {
            protected override string RemoteTableName => "empire_icon_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(EmpireIconDesc row) => row.Id;

                public IdUniqueIndex(EmpireIconDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal EmpireIconDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(EmpireIconDesc row) => row.Id;
        }

        public readonly EmpireIconDescHandle EmpireIconDesc;
    }
}
