// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EmpireColorDescHandle : RemoteTableHandle<EventContext, EmpireColorDesc>
        {
            protected override string RemoteTableName => "empire_color_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(EmpireColorDesc row) => row.Id;

                public IdUniqueIndex(EmpireColorDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal EmpireColorDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(EmpireColorDesc row) => row.Id;
        }

        public readonly EmpireColorDescHandle EmpireColorDesc;
    }
}
