// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EmpireStateHandle : RemoteTableHandle<EventContext, EmpireState>
        {
            protected override string RemoteTableName => "empire_state";

            public sealed class CapitalBuildingEntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EmpireState row) => row.CapitalBuildingEntityId;

                public CapitalBuildingEntityIdUniqueIndex(EmpireStateHandle table) : base(table) { }
            }

            public readonly CapitalBuildingEntityIdUniqueIndex CapitalBuildingEntityId;

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EmpireState row) => row.EntityId;

                public EntityIdUniqueIndex(EmpireStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class NameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(EmpireState row) => row.Name;

                public NameUniqueIndex(EmpireStateHandle table) : base(table) { }
            }

            public readonly NameUniqueIndex Name;

            internal EmpireStateHandle(DbConnection conn) : base(conn)
            {
                CapitalBuildingEntityId = new(this);
                EntityId = new(this);
                Name = new(this);
            }

            protected override object GetPrimaryKey(EmpireState row) => row.EntityId;
        }

        public readonly EmpireStateHandle EmpireState;
    }
}
