// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit dev).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EmpireSuppliesDescHandle : RemoteTableHandle<EventContext, EmpireSuppliesDesc>
        {
            protected override string RemoteTableName => "empire_supplies_desc";

            public sealed class CargoIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(EmpireSuppliesDesc row) => row.CargoId;

                public CargoIdUniqueIndex(EmpireSuppliesDescHandle table) : base(table) { }
            }

            public readonly CargoIdUniqueIndex CargoId;

            internal EmpireSuppliesDescHandle(DbConnection conn) : base(conn)
            {
                CargoId = new(this);
            }

            protected override object GetPrimaryKey(EmpireSuppliesDesc row) => row.CargoId;
        }

        public readonly EmpireSuppliesDescHandle EmpireSuppliesDesc;
    }
}
