// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EmpireChunkStateHandle : RemoteTableHandle<EventContext, EmpireChunkState>
        {
            protected override string RemoteTableName => "empire_chunk_state";

            public sealed class ChunkIndexUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EmpireChunkState row) => row.ChunkIndex;

                public ChunkIndexUniqueIndex(EmpireChunkStateHandle table) : base(table) { }
            }

            public readonly ChunkIndexUniqueIndex ChunkIndex;

            internal EmpireChunkStateHandle(DbConnection conn) : base(conn)
            {
                ChunkIndex = new(this);
            }

            protected override object GetPrimaryKey(EmpireChunkState row) => row.ChunkIndex;
        }

        public readonly EmpireChunkStateHandle EmpireChunkState;
    }
}
