// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EndGracePeriodTimerHandle : RemoteTableHandle<EventContext, EndGracePeriodTimer>
        {
            protected override string RemoteTableName => "end_grace_period_timer";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(EndGracePeriodTimer row) => row.Identity;

                public IdentityUniqueIndex(EndGracePeriodTimerHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EndGracePeriodTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(EndGracePeriodTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal EndGracePeriodTimerHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(EndGracePeriodTimer row) => row.ScheduledId;
        }

        public readonly EndGracePeriodTimerHandle EndGracePeriodTimer;
    }
}
