// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnemyMobMonitorStateHandle : RemoteTableHandle<EventContext, EnemyMobMonitorState>
        {
            protected override string RemoteTableName => "enemy_mob_monitor_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EnemyMobMonitorState row) => row.EntityId;

                public EntityIdUniqueIndex(EnemyMobMonitorStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal EnemyMobMonitorStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(EnemyMobMonitorState row) => row.EntityId;
        }

        public readonly EnemyMobMonitorStateHandle EnemyMobMonitorState;
    }
}
