// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnemyDespawnTimerHandle : RemoteTableHandle<EventContext, EnemyDespawnTimer>
        {
            protected override string RemoteTableName => "enemy_despawn_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EnemyDespawnTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(EnemyDespawnTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal EnemyDespawnTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(EnemyDespawnTimer row) => row.ScheduledId;
        }

        public readonly EnemyDespawnTimerHandle EnemyDespawnTimer;
    }
}
