// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnemyDescHandle : RemoteTableHandle<EventContext, EnemyDesc>
        {
            protected override string RemoteTableName => "enemy_desc";

            public sealed class EnemyTypeUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(EnemyDesc row) => row.EnemyType;

                public EnemyTypeUniqueIndex(EnemyDescHandle table) : base(table) { }
            }

            public readonly EnemyTypeUniqueIndex EnemyType;

            internal EnemyDescHandle(DbConnection conn) : base(conn)
            {
                EnemyType = new(this);
            }

            protected override object GetPrimaryKey(EnemyDesc row) => row.EnemyType;
        }

        public readonly EnemyDescHandle EnemyDesc;
    }
}
