// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnvironmentDebuffLoopTimerHandle : RemoteTableHandle<EventContext, EnvironmentDebuffLoopTimer>
        {
            protected override string RemoteTableName => "environment_debuff_loop_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EnvironmentDebuffLoopTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(EnvironmentDebuffLoopTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal EnvironmentDebuffLoopTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(EnvironmentDebuffLoopTimer row) => row.ScheduledId;
        }

        public readonly EnvironmentDebuffLoopTimerHandle EnvironmentDebuffLoopTimer;
    }
}
