// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnvironmentDebuffDescHandle : RemoteTableHandle<EventContext, EnvironmentDebuffDesc>
        {
            protected override string RemoteTableName => "environment_debuff_desc";

            public sealed class BuffIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(EnvironmentDebuffDesc row) => row.BuffId;

                public BuffIdUniqueIndex(EnvironmentDebuffDescHandle table) : base(table) { }
            }

            public readonly BuffIdUniqueIndex BuffId;

            internal EnvironmentDebuffDescHandle(DbConnection conn) : base(conn)
            {
                BuffId = new(this);
            }

            protected override object GetPrimaryKey(EnvironmentDebuffDesc row) => row.BuffId;
        }

        public readonly EnvironmentDebuffDescHandle EnvironmentDebuffDesc;
    }
}
