// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ExperienceStateHandle : RemoteTableHandle<EventContext, ExperienceState>
        {
            protected override string RemoteTableName => "experience_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ExperienceState row) => row.EntityId;

                public EntityIdUniqueIndex(ExperienceStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal ExperienceStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(ExperienceState row) => row.EntityId;
        }

        public readonly ExperienceStateHandle ExperienceState;
    }
}
