// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ExtractOutcomeStateHandle : RemoteTableHandle<EventContext, ExtractOutcomeState>
        {
            protected override string RemoteTableName => "extract_outcome_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ExtractOutcomeState row) => row.EntityId;

                public EntityIdUniqueIndex(ExtractOutcomeStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal ExtractOutcomeStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(ExtractOutcomeState row) => row.EntityId;
        }

        public readonly ExtractOutcomeStateHandle ExtractOutcomeState;
    }
}
