// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ExtractionRecipeDescHandle : RemoteTableHandle<EventContext, ExtractionRecipeDesc>
        {
            protected override string RemoteTableName => "extraction_recipe_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ExtractionRecipeDesc row) => row.Id;

                public IdUniqueIndex(ExtractionRecipeDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ResourceIdIndex : BTreeIndexBase<int>
            {
                protected override int GetKey(ExtractionRecipeDesc row) => row.ResourceId;

                public ResourceIdIndex(ExtractionRecipeDescHandle table) : base(table) { }
            }

            public readonly ResourceIdIndex ResourceId;

            internal ExtractionRecipeDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ResourceId = new(this);
            }

            protected override object GetPrimaryKey(ExtractionRecipeDesc row) => row.Id;
        }

        public readonly ExtractionRecipeDescHandle ExtractionRecipeDesc;
    }
}
