// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ForceGenerateTypesHandle : RemoteTableHandle<EventContext, ForceGenerateTypes>
        {
            protected override string RemoteTableName => "force_generate_types";

            internal ForceGenerateTypesHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly ForceGenerateTypesHandle ForceGenerateTypes;
    }
}
