// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GlobalsHandle : RemoteTableHandle<EventContext, Globals>
        {
            protected override string RemoteTableName => "globals";

            public sealed class VersionUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(Globals row) => row.Version;

                public VersionUniqueIndex(GlobalsHandle table) : base(table) { }
            }

            public readonly VersionUniqueIndex Version;

            internal GlobalsHandle(DbConnection conn) : base(conn)
            {
                Version = new(this);
            }

            protected override object GetPrimaryKey(Globals row) => row.Version;
        }

        public readonly GlobalsHandle Globals;
    }
}
