// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GrowthLoopTimerHandle : RemoteTableHandle<EventContext, GrowthLoopTimer>
        {
            protected override string RemoteTableName => "growth_loop_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(GrowthLoopTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(GrowthLoopTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal GrowthLoopTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(GrowthLoopTimer row) => row.ScheduledId;
        }

        public readonly GrowthLoopTimerHandle GrowthLoopTimer;
    }
}
