// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class HerdStateHandle : RemoteTableHandle<EventContext, HerdState>
        {
            protected override string RemoteTableName => "herd_state";

            public sealed class EnemyAiParamsDescIdIndex : BTreeIndexBase<int>
            {
                protected override int GetKey(HerdState row) => row.EnemyAiParamsDescId;

                public EnemyAiParamsDescIdIndex(HerdStateHandle table) : base(table) { }
            }

            public readonly EnemyAiParamsDescIdIndex EnemyAiParamsDescId;

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(HerdState row) => row.EntityId;

                public EntityIdUniqueIndex(HerdStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal HerdStateHandle(DbConnection conn) : base(conn)
            {
                EnemyAiParamsDescId = new(this);
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(HerdState row) => row.EntityId;
        }

        public readonly HerdStateHandle HerdState;
    }
}
