// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class IdentityRoleHandle : RemoteTableHandle<EventContext, IdentityRole>
        {
            protected override string RemoteTableName => "identity_role";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(IdentityRole row) => row.Identity;

                public IdentityUniqueIndex(IdentityRoleHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal IdentityRoleHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(IdentityRole row) => row.Identity;
        }

        public readonly IdentityRoleHandle IdentityRole;
    }
}
