// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class InteriorPlayerCountStateHandle : RemoteTableHandle<EventContext, InteriorPlayerCountState>
        {
            protected override string RemoteTableName => "interior_player_count_state";

            public sealed class DimensionNetworkEntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(InteriorPlayerCountState row) => row.DimensionNetworkEntityId;

                public DimensionNetworkEntityIdUniqueIndex(InteriorPlayerCountStateHandle table) : base(table) { }
            }

            public readonly DimensionNetworkEntityIdUniqueIndex DimensionNetworkEntityId;

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(InteriorPlayerCountState row) => row.EntityId;

                public EntityIdUniqueIndex(InteriorPlayerCountStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal InteriorPlayerCountStateHandle(DbConnection conn) : base(conn)
            {
                DimensionNetworkEntityId = new(this);
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(InteriorPlayerCountState row) => row.EntityId;
        }

        public readonly InteriorPlayerCountStateHandle InteriorPlayerCountState;
    }
}
