// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class InterModuleResponseMessageCounterHandle : RemoteTableHandle<EventContext, InterModuleResponseMessageCounter>
        {
            protected override string RemoteTableName => "inter_module_response_message_counter";

            public sealed class DstModuleIdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(InterModuleResponseMessageCounter row) => row.DstModuleId;

                public DstModuleIdUniqueIndex(InterModuleResponseMessageCounterHandle table) : base(table) { }
            }

            public readonly DstModuleIdUniqueIndex DstModuleId;

            internal InterModuleResponseMessageCounterHandle(DbConnection conn) : base(conn)
            {
                DstModuleId = new(this);
            }

            protected override object GetPrimaryKey(InterModuleResponseMessageCounter row) => row.DstModuleId;
        }

        public readonly InterModuleResponseMessageCounterHandle InterModuleResponseMessageCounter;
    }
}
