// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class InteriorSetCollapsedTimerHandle : RemoteTableHandle<EventContext, InteriorSetCollapsedTimer>
        {
            protected override string RemoteTableName => "interior_set_collapsed_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(InteriorSetCollapsedTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(InteriorSetCollapsedTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal InteriorSetCollapsedTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(InteriorSetCollapsedTimer row) => row.ScheduledId;
        }

        public readonly InteriorSetCollapsedTimerHandle InteriorSetCollapsedTimer;
    }
}
