// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class InterModuleMessageHandle : RemoteTableHandle<EventContext, InterModuleMessage>
        {
            protected override string RemoteTableName => "inter_module_message";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(InterModuleMessage row) => row.Id;

                public IdUniqueIndex(InterModuleMessageHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal InterModuleMessageHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(InterModuleMessage row) => row.Id;
        }

        public readonly InterModuleMessageHandle InterModuleMessage;
    }
}
