// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class InteriorSpawnDescHandle : RemoteTableHandle<EventContext, InteriorSpawnDesc>
        {
            protected override string RemoteTableName => "interior_spawn_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(InteriorSpawnDesc row) => row.Id;

                public IdUniqueIndex(InteriorSpawnDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class InteriorInstanceIdIndex : BTreeIndexBase<int>
            {
                protected override int GetKey(InteriorSpawnDesc row) => row.InteriorInstanceId;

                public InteriorInstanceIdIndex(InteriorSpawnDescHandle table) : base(table) { }
            }

            public readonly InteriorInstanceIdIndex InteriorInstanceId;

            internal InteriorSpawnDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                InteriorInstanceId = new(this);
            }

            protected override object GetPrimaryKey(InteriorSpawnDesc row) => row.Id;
        }

        public readonly InteriorSpawnDescHandle InteriorSpawnDesc;
    }
}
