// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class InteriorEnvironmentDescHandle : RemoteTableHandle<EventContext, InteriorEnvironmentDesc>
        {
            protected override string RemoteTableName => "interior_environment_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(InteriorEnvironmentDesc row) => row.Id;

                public IdUniqueIndex(InteriorEnvironmentDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal InteriorEnvironmentDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(InteriorEnvironmentDesc row) => row.Id;
        }

        public readonly InteriorEnvironmentDescHandle InteriorEnvironmentDesc;
    }
}
