// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class InterModuleMessageCounterHandle : RemoteTableHandle<EventContext, InterModuleMessageCounter>
        {
            protected override string RemoteTableName => "inter_module_message_counter";

            public sealed class ModuleIdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(InterModuleMessageCounter row) => row.ModuleId;

                public ModuleIdUniqueIndex(InterModuleMessageCounterHandle table) : base(table) { }
            }

            public readonly ModuleIdUniqueIndex ModuleId;

            internal InterModuleMessageCounterHandle(DbConnection conn) : base(conn)
            {
                ModuleId = new(this);
            }

            protected override object GetPrimaryKey(InterModuleMessageCounter row) => row.ModuleId;
        }

        public readonly InterModuleMessageCounterHandle InterModuleMessageCounter;
    }
}
