// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class InteriorNetworkDescHandle : RemoteTableHandle<EventContext, InteriorNetworkDesc>
        {
            protected override string RemoteTableName => "interior_network_desc";

            public sealed class BuildingIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(InteriorNetworkDesc row) => row.BuildingId;

                public BuildingIdUniqueIndex(InteriorNetworkDescHandle table) : base(table) { }
            }

            public readonly BuildingIdUniqueIndex BuildingId;

            internal InteriorNetworkDescHandle(DbConnection conn) : base(conn)
            {
                BuildingId = new(this);
            }

            protected override object GetPrimaryKey(InteriorNetworkDesc row) => row.BuildingId;
        }

        public readonly InteriorNetworkDescHandle InteriorNetworkDesc;
    }
}
