// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class InventoryStateHandle : RemoteTableHandle<EventContext, InventoryState>
        {
            protected override string RemoteTableName => "inventory_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(InventoryState row) => row.EntityId;

                public EntityIdUniqueIndex(InventoryStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class OwnerEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(InventoryState row) => row.OwnerEntityId;

                public OwnerEntityIdIndex(InventoryStateHandle table) : base(table) { }
            }

            public readonly OwnerEntityIdIndex OwnerEntityId;

            public sealed class PlayerOwnerEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(InventoryState row) => row.PlayerOwnerEntityId;

                public PlayerOwnerEntityIdIndex(InventoryStateHandle table) : base(table) { }
            }

            public readonly PlayerOwnerEntityIdIndex PlayerOwnerEntityId;

            internal InventoryStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                OwnerEntityId = new(this);
                PlayerOwnerEntityId = new(this);
            }

            protected override object GetPrimaryKey(InventoryState row) => row.EntityId;
        }

        public readonly InventoryStateHandle InventoryState;
    }
}
