// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ItemListDescHandle : RemoteTableHandle<EventContext, ItemListDesc>
        {
            protected override string RemoteTableName => "item_list_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ItemListDesc row) => row.Id;

                public IdUniqueIndex(ItemListDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ItemListDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ItemListDesc row) => row.Id;
        }

        public readonly ItemListDescHandle ItemListDesc;
    }
}
