// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class KnowledgeBattleActionStateHandle : RemoteTableHandle<EventContext, KnowledgeBattleActionState>
        {
            protected override string RemoteTableName => "knowledge_battle_action_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(KnowledgeBattleActionState row) => row.EntityId;

                public EntityIdUniqueIndex(KnowledgeBattleActionStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal KnowledgeBattleActionStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(KnowledgeBattleActionState row) => row.EntityId;
        }

        public readonly KnowledgeBattleActionStateHandle KnowledgeBattleActionState;
    }
}
