// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class KnowledgeItemStateHandle : RemoteTableHandle<EventContext, KnowledgeItemState>
        {
            protected override string RemoteTableName => "knowledge_item_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(KnowledgeItemState row) => row.EntityId;

                public EntityIdUniqueIndex(KnowledgeItemStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal KnowledgeItemStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(KnowledgeItemState row) => row.EntityId;
        }

        public readonly KnowledgeItemStateHandle KnowledgeItemState;
    }
}
