// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class KnowledgeResourcePlacementStateHandle : RemoteTableHandle<EventContext, KnowledgeResourcePlacementState>
        {
            protected override string RemoteTableName => "knowledge_resource_placement_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(KnowledgeResourcePlacementState row) => row.EntityId;

                public EntityIdUniqueIndex(KnowledgeResourcePlacementStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal KnowledgeResourcePlacementStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(KnowledgeResourcePlacementState row) => row.EntityId;
        }

        public readonly KnowledgeResourcePlacementStateHandle KnowledgeResourcePlacementState;
    }
}
