// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class KnowledgeClaimStateHandle : RemoteTableHandle<EventContext, KnowledgeClaimState>
        {
            protected override string RemoteTableName => "knowledge_claim_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(KnowledgeClaimState row) => row.EntityId;

                public EntityIdUniqueIndex(KnowledgeClaimStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal KnowledgeClaimStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(KnowledgeClaimState row) => row.EntityId;
        }

        public readonly KnowledgeClaimStateHandle KnowledgeClaimState;
    }
}
