// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class KnowledgeResourceStateHandle : RemoteTableHandle<EventContext, KnowledgeResourceState>
        {
            protected override string RemoteTableName => "knowledge_resource_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(KnowledgeResourceState row) => row.EntityId;

                public EntityIdUniqueIndex(KnowledgeResourceStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal KnowledgeResourceStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(KnowledgeResourceState row) => row.EntityId;
        }

        public readonly KnowledgeResourceStateHandle KnowledgeResourceState;
    }
}
