// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class KnowledgeScrollTypeDescHandle : RemoteTableHandle<EventContext, KnowledgeScrollTypeDesc>
        {
            protected override string RemoteTableName => "knowledge_scroll_type_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(KnowledgeScrollTypeDesc row) => row.Id;

                public IdUniqueIndex(KnowledgeScrollTypeDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal KnowledgeScrollTypeDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(KnowledgeScrollTypeDesc row) => row.Id;
        }

        public readonly KnowledgeScrollTypeDescHandle KnowledgeScrollTypeDesc;
    }
}
