// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class KnowledgeStatModifierDescHandle : RemoteTableHandle<EventContext, KnowledgeStatModifierDesc>
        {
            protected override string RemoteTableName => "knowledge_stat_modifier_desc";

            public sealed class SecondaryKnowledgeIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(KnowledgeStatModifierDesc row) => row.SecondaryKnowledgeId;

                public SecondaryKnowledgeIdUniqueIndex(KnowledgeStatModifierDescHandle table) : base(table) { }
            }

            public readonly SecondaryKnowledgeIdUniqueIndex SecondaryKnowledgeId;

            internal KnowledgeStatModifierDescHandle(DbConnection conn) : base(conn)
            {
                SecondaryKnowledgeId = new(this);
            }

            protected override object GetPrimaryKey(KnowledgeStatModifierDesc row) => row.SecondaryKnowledgeId;
        }

        public readonly KnowledgeStatModifierDescHandle KnowledgeStatModifierDesc;
    }
}
