// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class KnowledgeVaultStateHandle : RemoteTableHandle<EventContext, KnowledgeVaultState>
        {
            protected override string RemoteTableName => "knowledge_vault_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(KnowledgeVaultState row) => row.EntityId;

                public EntityIdUniqueIndex(KnowledgeVaultStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal KnowledgeVaultStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(KnowledgeVaultState row) => row.EntityId;
        }

        public readonly KnowledgeVaultStateHandle KnowledgeVaultState;
    }
}
