// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LootChestDespawnTimerHandle : RemoteTableHandle<EventContext, LootChestDespawnTimer>
        {
            protected override string RemoteTableName => "loot_chest_despawn_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(LootChestDespawnTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(LootChestDespawnTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal LootChestDespawnTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(LootChestDespawnTimer row) => row.ScheduledId;
        }

        public readonly LootChestDespawnTimerHandle LootChestDespawnTimer;
    }
}
