// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ModerationActionLogEntryHandle : RemoteTableHandle<EventContext, ModerationActionLogEntry>
        {
            protected override string RemoteTableName => "moderation_action_log_entry";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ModerationActionLogEntry row) => row.EntityId;

                public EntityIdUniqueIndex(ModerationActionLogEntryHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class ReportEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(ModerationActionLogEntry row) => row.ReportEntityId;

                public ReportEntityIdIndex(ModerationActionLogEntryHandle table) : base(table) { }
            }

            public readonly ReportEntityIdIndex ReportEntityId;

            public sealed class ReportedPlayerEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(ModerationActionLogEntry row) => row.ReportedPlayerEntityId;

                public ReportedPlayerEntityIdIndex(ModerationActionLogEntryHandle table) : base(table) { }
            }

            public readonly ReportedPlayerEntityIdIndex ReportedPlayerEntityId;

            internal ModerationActionLogEntryHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                ReportEntityId = new(this);
                ReportedPlayerEntityId = new(this);
            }

            protected override object GetPrimaryKey(ModerationActionLogEntry row) => row.EntityId;
        }

        public readonly ModerationActionLogEntryHandle ModerationActionLogEntry;
    }
}
