// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MountingStateHandle : RemoteTableHandle<EventContext, MountingState>
        {
            protected override string RemoteTableName => "mounting_state";

            public sealed class DeployableEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(MountingState row) => row.DeployableEntityId;

                public DeployableEntityIdIndex(MountingStateHandle table) : base(table) { }
            }

            public readonly DeployableEntityIdIndex DeployableEntityId;

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MountingState row) => row.EntityId;

                public EntityIdUniqueIndex(MountingStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal MountingStateHandle(DbConnection conn) : base(conn)
            {
                DeployableEntityId = new(this);
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(MountingState row) => row.EntityId;
        }

        public readonly MountingStateHandle MountingState;
    }
}
