// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MoveValidationStrikeCounterStateHandle : RemoteTableHandle<EventContext, MoveValidationStrikeCounterState>
        {
            protected override string RemoteTableName => "move_validation_strike_counter_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MoveValidationStrikeCounterState row) => row.EntityId;

                public EntityIdUniqueIndex(MoveValidationStrikeCounterStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal MoveValidationStrikeCounterStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(MoveValidationStrikeCounterState row) => row.EntityId;
        }

        public readonly MoveValidationStrikeCounterStateHandle MoveValidationStrikeCounterState;
    }
}
