// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NpcDescHandle : RemoteTableHandle<EventContext, NpcDesc>
        {
            protected override string RemoteTableName => "npc_desc";

            public sealed class NpcTypeUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(NpcDesc row) => row.NpcType;

                public NpcTypeUniqueIndex(NpcDescHandle table) : base(table) { }
            }

            public readonly NpcTypeUniqueIndex NpcType;

            internal NpcDescHandle(DbConnection conn) : base(conn)
            {
                NpcType = new(this);
            }

            protected override object GetPrimaryKey(NpcDesc row) => row.NpcType;
        }

        public readonly NpcDescHandle NpcDesc;
    }
}
