// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NpcStateHandle : RemoteTableHandle<EventContext, NpcState>
        {
            protected override string RemoteTableName => "npc_state";

            public sealed class BuildingEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(NpcState row) => row.BuildingEntityId;

                public BuildingEntityIdIndex(NpcStateHandle table) : base(table) { }
            }

            public readonly BuildingEntityIdIndex BuildingEntityId;

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(NpcState row) => row.EntityId;

                public EntityIdUniqueIndex(NpcStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal NpcStateHandle(DbConnection conn) : base(conn)
            {
                BuildingEntityId = new(this);
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(NpcState row) => row.EntityId;
        }

        public readonly NpcStateHandle NpcState;
    }
}
