// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class OnboardingRewardDescHandle : RemoteTableHandle<EventContext, OnboardingRewardDesc>
        {
            protected override string RemoteTableName => "onboarding_reward_desc";

            public sealed class StateIdUniqueIndex : UniqueIndexBase<ushort>
            {
                protected override ushort GetKey(OnboardingRewardDesc row) => row.StateId;

                public StateIdUniqueIndex(OnboardingRewardDescHandle table) : base(table) { }
            }

            public readonly StateIdUniqueIndex StateId;

            internal OnboardingRewardDescHandle(DbConnection conn) : base(conn)
            {
                StateId = new(this);
            }

            protected override object GetPrimaryKey(OnboardingRewardDesc row) => row.StateId;
        }

        public readonly OnboardingRewardDescHandle OnboardingRewardDesc;
    }
}
