// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ParametersPlayerMoveDescHandle : RemoteTableHandle<EventContext, ParametersPlayerMoveDesc>
        {
            protected override string RemoteTableName => "parameters_player_move_desc";

            public sealed class VersionUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ParametersPlayerMoveDesc row) => row.Version;

                public VersionUniqueIndex(ParametersPlayerMoveDescHandle table) : base(table) { }
            }

            public readonly VersionUniqueIndex Version;

            internal ParametersPlayerMoveDescHandle(DbConnection conn) : base(conn)
            {
                Version = new(this);
            }

            protected override object GetPrimaryKey(ParametersPlayerMoveDesc row) => row.Version;
        }

        public readonly ParametersPlayerMoveDescHandle ParametersPlayerMoveDesc;
    }
}
