// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PassiveCraftTimerHandle : RemoteTableHandle<EventContext, PassiveCraftTimer>
        {
            protected override string RemoteTableName => "passive_craft_timer";

            public sealed class CraftEntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PassiveCraftTimer row) => row.CraftEntityId;

                public CraftEntityIdUniqueIndex(PassiveCraftTimerHandle table) : base(table) { }
            }

            public readonly CraftEntityIdUniqueIndex CraftEntityId;

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PassiveCraftTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(PassiveCraftTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal PassiveCraftTimerHandle(DbConnection conn) : base(conn)
            {
                CraftEntityId = new(this);
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(PassiveCraftTimer row) => row.ScheduledId;
        }

        public readonly PassiveCraftTimerHandle PassiveCraftTimer;
    }
}
