// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PavedTileStateHandle : RemoteTableHandle<EventContext, PavedTileState>
        {
            protected override string RemoteTableName => "paved_tile_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PavedTileState row) => row.EntityId;

                public EntityIdUniqueIndex(PavedTileStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal PavedTileStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(PavedTileState row) => row.EntityId;
        }

        public readonly PavedTileStateHandle PavedTileState;
    }
}
