// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PavingTileDescHandle : RemoteTableHandle<EventContext, PavingTileDesc>
        {
            protected override string RemoteTableName => "paving_tile_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(PavingTileDesc row) => row.Id;

                public IdUniqueIndex(PavingTileDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal PavingTileDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(PavingTileDesc row) => row.Id;
        }

        public readonly PavingTileDescHandle PavingTileDesc;
    }
}
