// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerUseElevatorTimerHandle : RemoteTableHandle<EventContext, PlayerUseElevatorTimer>
        {
            protected override string RemoteTableName => "player_use_elevator_timer";

            public sealed class DestinationPlatformEntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerUseElevatorTimer row) => row.DestinationPlatformEntityId;

                public DestinationPlatformEntityIdUniqueIndex(PlayerUseElevatorTimerHandle table) : base(table) { }
            }

            public readonly DestinationPlatformEntityIdUniqueIndex DestinationPlatformEntityId;

            public sealed class OriginPlatformEntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerUseElevatorTimer row) => row.OriginPlatformEntityId;

                public OriginPlatformEntityIdUniqueIndex(PlayerUseElevatorTimerHandle table) : base(table) { }
            }

            public readonly OriginPlatformEntityIdUniqueIndex OriginPlatformEntityId;

            public sealed class PlayerEntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerUseElevatorTimer row) => row.PlayerEntityId;

                public PlayerEntityIdUniqueIndex(PlayerUseElevatorTimerHandle table) : base(table) { }
            }

            public readonly PlayerEntityIdUniqueIndex PlayerEntityId;

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerUseElevatorTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(PlayerUseElevatorTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal PlayerUseElevatorTimerHandle(DbConnection conn) : base(conn)
            {
                DestinationPlatformEntityId = new(this);
                OriginPlatformEntityId = new(this);
                PlayerEntityId = new(this);
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(PlayerUseElevatorTimer row) => row.ScheduledId;
        }

        public readonly PlayerUseElevatorTimerHandle PlayerUseElevatorTimer;
    }
}
