// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerReportStateTimestampHandle : RemoteTableHandle<EventContext, PlayerReportStateTimestamp>
        {
            protected override string RemoteTableName => "player_report_state_timestamp";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerReportStateTimestamp row) => row.EntityId;

                public EntityIdUniqueIndex(PlayerReportStateTimestampHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal PlayerReportStateTimestampHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(PlayerReportStateTimestamp row) => row.EntityId;
        }

        public readonly PlayerReportStateTimestampHandle PlayerReportStateTimestamp;
    }
}
