// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerHousingStateHandle : RemoteTableHandle<EventContext, PlayerHousingState>
        {
            protected override string RemoteTableName => "player_housing_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerHousingState row) => row.EntityId;

                public EntityIdUniqueIndex(PlayerHousingStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class EntranceBuildingEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerHousingState row) => row.EntranceBuildingEntityId;

                public EntranceBuildingEntityIdIndex(PlayerHousingStateHandle table) : base(table) { }
            }

            public readonly EntranceBuildingEntityIdIndex EntranceBuildingEntityId;

            public sealed class NetworkEntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerHousingState row) => row.NetworkEntityId;

                public NetworkEntityIdUniqueIndex(PlayerHousingStateHandle table) : base(table) { }
            }

            public readonly NetworkEntityIdUniqueIndex NetworkEntityId;

            internal PlayerHousingStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                EntranceBuildingEntityId = new(this);
                NetworkEntityId = new(this);
            }

            protected override object GetPrimaryKey(PlayerHousingState row) => row.EntityId;
        }

        public readonly PlayerHousingStateHandle PlayerHousingState;
    }
}
