// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit dev).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerHousingEvictPlayerTimerHandle : RemoteTableHandle<EventContext, PlayerHousingEvictPlayerTimer>
        {
            protected override string RemoteTableName => "player_housing_evict_player_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerHousingEvictPlayerTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(PlayerHousingEvictPlayerTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal PlayerHousingEvictPlayerTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(PlayerHousingEvictPlayerTimer row) => row.ScheduledId;
        }

        public readonly PlayerHousingEvictPlayerTimerHandle PlayerHousingEvictPlayerTimer;
    }
}
