// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerVoteConcludeTimerHandle : RemoteTableHandle<EventContext, PlayerVoteConcludeTimer>
        {
            protected override string RemoteTableName => "player_vote_conclude_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerVoteConcludeTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(PlayerVoteConcludeTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal PlayerVoteConcludeTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(PlayerVoteConcludeTimer row) => row.ScheduledId;
        }

        public readonly PlayerVoteConcludeTimerHandle PlayerVoteConcludeTimer;
    }
}
