// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerHousingMovingCostStateHandle : RemoteTableHandle<EventContext, PlayerHousingMovingCostState>
        {
            protected override string RemoteTableName => "player_housing_moving_cost_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerHousingMovingCostState row) => row.EntityId;

                public EntityIdUniqueIndex(PlayerHousingMovingCostStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal PlayerHousingMovingCostStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(PlayerHousingMovingCostState row) => row.EntityId;
        }

        public readonly PlayerHousingMovingCostStateHandle PlayerHousingMovingCostState;
    }
}
