// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerActionDescHandle : RemoteTableHandle<EventContext, PlayerActionDesc>
        {
            protected override string RemoteTableName => "player_action_desc";

            public sealed class ActionTypeIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(PlayerActionDesc row) => row.ActionTypeId;

                public ActionTypeIdUniqueIndex(PlayerActionDescHandle table) : base(table) { }
            }

            public readonly ActionTypeIdUniqueIndex ActionTypeId;

            internal PlayerActionDescHandle(DbConnection conn) : base(conn)
            {
                ActionTypeId = new(this);
            }

            protected override object GetPrimaryKey(PlayerActionDesc row) => row.ActionTypeId;
        }

        public readonly PlayerActionDescHandle PlayerActionDesc;
    }
}
