// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerNotificationEventHandle : RemoteTableHandle<EventContext, PlayerNotificationEvent>
        {
            protected override string RemoteTableName => "player_notification_event";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerNotificationEvent row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(PlayerNotificationEventHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal PlayerNotificationEventHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(PlayerNotificationEvent row) => row.ScheduledId;
        }

        public readonly PlayerNotificationEventHandle PlayerNotificationEvent;
    }
}
