// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerNoteStateHandle : RemoteTableHandle<EventContext, PlayerNoteState>
        {
            protected override string RemoteTableName => "player_note_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerNoteState row) => row.EntityId;

                public EntityIdUniqueIndex(PlayerNoteStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal PlayerNoteStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(PlayerNoteState row) => row.EntityId;
        }

        public readonly PlayerNoteStateHandle PlayerNoteState;
    }
}
