// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerHousingDescHandle : RemoteTableHandle<EventContext, PlayerHousingDesc>
        {
            protected override string RemoteTableName => "player_housing_desc";

            public sealed class SecondaryKnowledgeIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(PlayerHousingDesc row) => row.SecondaryKnowledgeId;

                public SecondaryKnowledgeIdUniqueIndex(PlayerHousingDescHandle table) : base(table) { }
            }

            public readonly SecondaryKnowledgeIdUniqueIndex SecondaryKnowledgeId;

            internal PlayerHousingDescHandle(DbConnection conn) : base(conn)
            {
                SecondaryKnowledgeId = new(this);
            }

            protected override object GetPrimaryKey(PlayerHousingDesc row) => row.SecondaryKnowledgeId;
        }

        public readonly PlayerHousingDescHandle PlayerHousingDesc;
    }
}
