// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PrivateParametersDescHandle : RemoteTableHandle<EventContext, PrivateParametersDesc>
        {
            protected override string RemoteTableName => "private_parameters_desc";

            public sealed class VersionUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(PrivateParametersDesc row) => row.Version;

                public VersionUniqueIndex(PrivateParametersDescHandle table) : base(table) { }
            }

            public readonly VersionUniqueIndex Version;

            internal PrivateParametersDescHandle(DbConnection conn) : base(conn)
            {
                Version = new(this);
            }

            protected override object GetPrimaryKey(PrivateParametersDesc row) => row.Version;
        }

        public readonly PrivateParametersDescHandle PrivateParametersDesc;
    }
}
