// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PublicProgressiveActionStateHandle : RemoteTableHandle<EventContext, PublicProgressiveActionState>
        {
            protected override string RemoteTableName => "public_progressive_action_state";

            public sealed class BuildingEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(PublicProgressiveActionState row) => row.BuildingEntityId;

                public BuildingEntityIdIndex(PublicProgressiveActionStateHandle table) : base(table) { }
            }

            public readonly BuildingEntityIdIndex BuildingEntityId;

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PublicProgressiveActionState row) => row.EntityId;

                public EntityIdUniqueIndex(PublicProgressiveActionStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal PublicProgressiveActionStateHandle(DbConnection conn) : base(conn)
            {
                BuildingEntityId = new(this);
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(PublicProgressiveActionState row) => row.EntityId;
        }

        public readonly PublicProgressiveActionStateHandle PublicProgressiveActionState;
    }
}
