// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class RegionPopulationInfoHandle : RemoteTableHandle<EventContext, RegionPopulationInfo>
        {
            protected override string RemoteTableName => "region_population_info";

            public sealed class RegionIdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(RegionPopulationInfo row) => row.RegionId;

                public RegionIdUniqueIndex(RegionPopulationInfoHandle table) : base(table) { }
            }

            public readonly RegionIdUniqueIndex RegionId;

            internal RegionPopulationInfoHandle(DbConnection conn) : base(conn)
            {
                RegionId = new(this);
            }

            protected override object GetPrimaryKey(RegionPopulationInfo row) => row.RegionId;
        }

        public readonly RegionPopulationInfoHandle RegionPopulationInfo;
    }
}
