// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class RegionSignInParametersHandle : RemoteTableHandle<EventContext, RegionSignInParameters>
        {
            protected override string RemoteTableName => "region_sign_in_parameters";

            public sealed class RegionIdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(RegionSignInParameters row) => row.RegionId;

                public RegionIdUniqueIndex(RegionSignInParametersHandle table) : base(table) { }
            }

            public readonly RegionIdUniqueIndex RegionId;

            internal RegionSignInParametersHandle(DbConnection conn) : base(conn)
            {
                RegionId = new(this);
            }

            protected override object GetPrimaryKey(RegionSignInParameters row) => row.RegionId;
        }

        public readonly RegionSignInParametersHandle RegionSignInParameters;
    }
}
