// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class RentStateHandle : RemoteTableHandle<EventContext, RentState>
        {
            protected override string RemoteTableName => "rent_state";

            public sealed class ClaimEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(RentState row) => row.ClaimEntityId;

                public ClaimEntityIdIndex(RentStateHandle table) : base(table) { }
            }

            public readonly ClaimEntityIdIndex ClaimEntityId;

            public sealed class DimensionNetworkIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(RentState row) => row.DimensionNetworkId;

                public DimensionNetworkIdUniqueIndex(RentStateHandle table) : base(table) { }
            }

            public readonly DimensionNetworkIdUniqueIndex DimensionNetworkId;

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(RentState row) => row.EntityId;

                public EntityIdUniqueIndex(RentStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal RentStateHandle(DbConnection conn) : base(conn)
            {
                ClaimEntityId = new(this);
                DimensionNetworkId = new(this);
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(RentState row) => row.EntityId;
        }

        public readonly RentStateHandle RentState;
    }
}
