// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ReservedNameDescHandle : RemoteTableHandle<EventContext, ReservedNameDesc>
        {
            protected override string RemoteTableName => "reserved_name_desc";

            public sealed class NameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ReservedNameDesc row) => row.Name;

                public NameUniqueIndex(ReservedNameDescHandle table) : base(table) { }
            }

            public readonly NameUniqueIndex Name;

            internal ReservedNameDescHandle(DbConnection conn) : base(conn)
            {
                Name = new(this);
            }

            protected override object GetPrimaryKey(ReservedNameDesc row) => row.Name;
        }

        public readonly ReservedNameDescHandle ReservedNameDesc;
    }
}
