// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ResourcePlacementRecipeDescHandle : RemoteTableHandle<EventContext, ResourcePlacementRecipeDesc>
        {
            protected override string RemoteTableName => "resource_placement_recipe_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ResourcePlacementRecipeDesc row) => row.Id;

                public IdUniqueIndex(ResourcePlacementRecipeDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ResourcePlacementRecipeDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ResourcePlacementRecipeDesc row) => row.Id;
        }

        public readonly ResourcePlacementRecipeDescHandle ResourcePlacementRecipeDesc;
    }
}
