// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ResourceDescHandle : RemoteTableHandle<EventContext, ResourceDesc>
        {
            protected override string RemoteTableName => "resource_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ResourceDesc row) => row.Id;

                public IdUniqueIndex(ResourceDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ResourceDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ResourceDesc row) => row.Id;
        }

        public readonly ResourceDescHandle ResourceDesc;
    }
}
