// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ResourceGrowthRecipeDescHandle : RemoteTableHandle<EventContext, ResourceGrowthRecipeDesc>
        {
            protected override string RemoteTableName => "resource_growth_recipe_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ResourceGrowthRecipeDesc row) => row.Id;

                public IdUniqueIndex(ResourceGrowthRecipeDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ResourceIdIndex : BTreeIndexBase<int>
            {
                protected override int GetKey(ResourceGrowthRecipeDesc row) => row.ResourceId;

                public ResourceIdIndex(ResourceGrowthRecipeDescHandle table) : base(table) { }
            }

            public readonly ResourceIdIndex ResourceId;

            internal ResourceGrowthRecipeDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                ResourceId = new(this);
            }

            protected override object GetPrimaryKey(ResourceGrowthRecipeDesc row) => row.Id;
        }

        public readonly ResourceGrowthRecipeDescHandle ResourceGrowthRecipeDesc;
    }
}
