// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class RespawnResourceInChunkTimerHandle : RemoteTableHandle<EventContext, RespawnResourceInChunkTimer>
        {
            protected override string RemoteTableName => "respawn_resource_in_chunk_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(RespawnResourceInChunkTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(RespawnResourceInChunkTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal RespawnResourceInChunkTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(RespawnResourceInChunkTimer row) => row.ScheduledId;
        }

        public readonly RespawnResourceInChunkTimerHandle RespawnResourceInChunkTimer;
    }
}
