// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class RezSickLongTermStateHandle : RemoteTableHandle<EventContext, RezSickLongTermState>
        {
            protected override string RemoteTableName => "rez_sick_long_term_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(RezSickLongTermState row) => row.EntityId;

                public EntityIdUniqueIndex(RezSickLongTermStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal RezSickLongTermStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(RezSickLongTermState row) => row.EntityId;
        }

        public readonly RezSickLongTermStateHandle RezSickLongTermState;
    }
}
