// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SecondaryKnowledgeDescHandle : RemoteTableHandle<EventContext, SecondaryKnowledgeDesc>
        {
            protected override string RemoteTableName => "secondary_knowledge_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(SecondaryKnowledgeDesc row) => row.Id;

                public IdUniqueIndex(SecondaryKnowledgeDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal SecondaryKnowledgeDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(SecondaryKnowledgeDesc row) => row.Id;
        }

        public readonly SecondaryKnowledgeDescHandle SecondaryKnowledgeDesc;
    }
}
