// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SellOrderStateHandle : RemoteTableHandle<EventContext, AuctionListingState>
        {
            protected override string RemoteTableName => "sell_order_state";

            public sealed class ClaimEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(AuctionListingState row) => row.ClaimEntityId;

                public ClaimEntityIdIndex(SellOrderStateHandle table) : base(table) { }
            }

            public readonly ClaimEntityIdIndex ClaimEntityId;

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(AuctionListingState row) => row.EntityId;

                public EntityIdUniqueIndex(SellOrderStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class ItemForClaimIndex : BTreeIndexBase<(int ItemId, int ItemType, ulong ClaimEntityId)>
            {
                protected override (int ItemId, int ItemType, ulong ClaimEntityId) GetKey(AuctionListingState row) => (row.ItemId, row.ItemType, row.ClaimEntityId);

                public ItemForClaimIndex(SellOrderStateHandle table) : base(table) { }
            }

            public readonly ItemForClaimIndex ItemForClaim;

            public sealed class OwnerForClaimIndex : BTreeIndexBase<(ulong OwnerEntityId, ulong ClaimEntityId)>
            {
                protected override (ulong OwnerEntityId, ulong ClaimEntityId) GetKey(AuctionListingState row) => (row.OwnerEntityId, row.ClaimEntityId);

                public OwnerForClaimIndex(SellOrderStateHandle table) : base(table) { }
            }

            public readonly OwnerForClaimIndex OwnerForClaim;

            internal SellOrderStateHandle(DbConnection conn) : base(conn)
            {
                ClaimEntityId = new(this);
                EntityId = new(this);
                ItemForClaim = new(this);
                OwnerForClaim = new(this);
            }

            protected override object GetPrimaryKey(AuctionListingState row) => row.EntityId;
        }

        public readonly SellOrderStateHandle SellOrderState;
    }
}
