// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ServerIdentityHandle : RemoteTableHandle<EventContext, ServerIdentity>
        {
            protected override string RemoteTableName => "server_identity";

            public sealed class VersionUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(ServerIdentity row) => row.Version;

                public VersionUniqueIndex(ServerIdentityHandle table) : base(table) { }
            }

            public readonly VersionUniqueIndex Version;

            internal ServerIdentityHandle(DbConnection conn) : base(conn)
            {
                Version = new(this);
            }

            protected override object GetPrimaryKey(ServerIdentity row) => row.Version;
        }

        public readonly ServerIdentityHandle ServerIdentity;
    }
}
