// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SingleResourceToClumpDescHandle : RemoteTableHandle<EventContext, SingleResourceToClumpDesc>
        {
            protected override string RemoteTableName => "single_resource_to_clump_desc";

            public sealed class ClumpIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(SingleResourceToClumpDesc row) => row.ClumpId;

                public ClumpIdUniqueIndex(SingleResourceToClumpDescHandle table) : base(table) { }
            }

            public readonly ClumpIdUniqueIndex ClumpId;

            public sealed class ResourceIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(SingleResourceToClumpDesc row) => row.ResourceId;

                public ResourceIdUniqueIndex(SingleResourceToClumpDescHandle table) : base(table) { }
            }

            public readonly ResourceIdUniqueIndex ResourceId;

            internal SingleResourceToClumpDescHandle(DbConnection conn) : base(conn)
            {
                ClumpId = new(this);
                ResourceId = new(this);
            }

            protected override object GetPrimaryKey(SingleResourceToClumpDesc row) => row.ResourceId;
        }

        public readonly SingleResourceToClumpDescHandle SingleResourceToClumpDesc;
    }
}
