// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SkillDescHandle : RemoteTableHandle<EventContext, SkillDesc>
        {
            protected override string RemoteTableName => "skill_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(SkillDesc row) => row.Id;

                public IdUniqueIndex(SkillDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class SkillTypeUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(SkillDesc row) => row.SkillType;

                public SkillTypeUniqueIndex(SkillDescHandle table) : base(table) { }
            }

            public readonly SkillTypeUniqueIndex SkillType;

            internal SkillDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                SkillType = new(this);
            }

            protected override object GetPrimaryKey(SkillDesc row) => row.Id;
        }

        public readonly SkillDescHandle SkillDesc;
    }
}
