// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedStaticDataHandle : RemoteTableHandle<EventContext, StagedStaticData>
        {
            protected override string RemoteTableName => "staged_static_data";

            public sealed class VersionUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(StagedStaticData row) => row.Version;

                public VersionUniqueIndex(StagedStaticDataHandle table) : base(table) { }
            }

            public readonly VersionUniqueIndex Version;

            internal StagedStaticDataHandle(DbConnection conn) : base(conn)
            {
                Version = new(this);
            }

            protected override object GetPrimaryKey(StagedStaticData row) => row.Version;
        }

        public readonly StagedStaticDataHandle StagedStaticData;
    }
}
