// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedStaticDataV2Handle : RemoteTableHandle<EventContext, StagedStaticDataV2>
        {
            protected override string RemoteTableName => "staged_static_data_v2";

            public sealed class VersionUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(StagedStaticDataV2 row) => row.Version;

                public VersionUniqueIndex(StagedStaticDataV2Handle table) : base(table) { }
            }

            public readonly VersionUniqueIndex Version;

            internal StagedStaticDataV2Handle(DbConnection conn) : base(conn)
            {
                Version = new(this);
            }

            protected override object GetPrimaryKey(StagedStaticDataV2 row) => row.Version;
        }

        public readonly StagedStaticDataV2Handle StagedStaticDataV2;
    }
}
