// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StaminaStateHandle : RemoteTableHandle<EventContext, StaminaState>
        {
            protected override string RemoteTableName => "stamina_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(StaminaState row) => row.EntityId;

                public EntityIdUniqueIndex(StaminaStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal StaminaStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(StaminaState row) => row.EntityId;
        }

        public readonly StaminaStateHandle StaminaState;
    }
}
