// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StarvingPlayerStateHandle : RemoteTableHandle<EventContext, StarvingPlayerState>
        {
            protected override string RemoteTableName => "starving_player_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(StarvingPlayerState row) => row.EntityId;

                public EntityIdUniqueIndex(StarvingPlayerStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal StarvingPlayerStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(StarvingPlayerState row) => row.EntityId;
        }

        public readonly StarvingPlayerStateHandle StarvingPlayerState;
    }
}
