// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StorageLogStateHandle : RemoteTableHandle<EventContext, ActionLogState>
        {
            protected override string RemoteTableName => "storage_log_state";

            public sealed class DaysSinceEpochIndex : BTreeIndexBase<int>
            {
                protected override int GetKey(ActionLogState row) => row.DaysSinceEpoch;

                public DaysSinceEpochIndex(StorageLogStateHandle table) : base(table) { }
            }

            public readonly DaysSinceEpochIndex DaysSinceEpoch;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ActionLogState row) => row.Id;

                public IdUniqueIndex(StorageLogStateHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class ObjectEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(ActionLogState row) => row.ObjectEntityId;

                public ObjectEntityIdIndex(StorageLogStateHandle table) : base(table) { }
            }

            public readonly ObjectEntityIdIndex ObjectEntityId;

            internal StorageLogStateHandle(DbConnection conn) : base(conn)
            {
                DaysSinceEpoch = new(this);
                Id = new(this);
                ObjectEntityId = new(this);
            }

            protected override object GetPrimaryKey(ActionLogState row) => row.Id;
        }

        public readonly StorageLogStateHandle StorageLogState;
    }
}
