// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TargetableStateHandle : RemoteTableHandle<EventContext, TargetableState>
        {
            protected override string RemoteTableName => "targetable_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(TargetableState row) => row.EntityId;

                public EntityIdUniqueIndex(TargetableStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal TargetableStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(TargetableState row) => row.EntityId;
        }

        public readonly TargetableStateHandle TargetableState;
    }
}
