// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TeleportPlayerTimerHandle : RemoteTableHandle<EventContext, TeleportPlayerTimer>
        {
            protected override string RemoteTableName => "teleport_player_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(TeleportPlayerTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(TeleportPlayerTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal TeleportPlayerTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(TeleportPlayerTimer row) => row.ScheduledId;
        }

        public readonly TeleportPlayerTimerHandle TeleportPlayerTimer;
    }
}
