// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TeleportItemDescHandle : RemoteTableHandle<EventContext, TeleportItemDesc>
        {
            protected override string RemoteTableName => "teleport_item_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(TeleportItemDesc row) => row.Id;

                public IdUniqueIndex(TeleportItemDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal TeleportItemDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(TeleportItemDesc row) => row.Id;
        }

        public readonly TeleportItemDescHandle TeleportItemDesc;
    }
}
