// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ToolTypeDescHandle : RemoteTableHandle<EventContext, ToolTypeDesc>
        {
            protected override string RemoteTableName => "tool_type_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ToolTypeDesc row) => row.Id;

                public IdUniqueIndex(ToolTypeDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class SkillIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ToolTypeDesc row) => row.SkillId;

                public SkillIdUniqueIndex(ToolTypeDescHandle table) : base(table) { }
            }

            public readonly SkillIdUniqueIndex SkillId;

            internal ToolTypeDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                SkillId = new(this);
            }

            protected override object GetPrimaryKey(ToolTypeDesc row) => row.Id;
        }

        public readonly ToolTypeDescHandle ToolTypeDesc;
    }
}
