// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TransferPlayerTimerHandle : RemoteTableHandle<EventContext, TransferPlayerTimer>
        {
            protected override string RemoteTableName => "transfer_player_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(TransferPlayerTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(TransferPlayerTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal TransferPlayerTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(TransferPlayerTimer row) => row.ScheduledId;
        }

        public readonly TransferPlayerTimerHandle TransferPlayerTimer;
    }
}
