// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UnclaimedShardsStateHandle : RemoteTableHandle<EventContext, UnclaimedShardsState>
        {
            protected override string RemoteTableName => "unclaimed_shards_state";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(UnclaimedShardsState row) => row.Identity;

                public IdentityUniqueIndex(UnclaimedShardsStateHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal UnclaimedShardsStateHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(UnclaimedShardsState row) => row.Identity;
        }

        public readonly UnclaimedShardsStateHandle UnclaimedShardsState;
    }
}
