// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UserModerationStateHandle : RemoteTableHandle<EventContext, UserModerationState>
        {
            protected override string RemoteTableName => "user_moderation_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(UserModerationState row) => row.EntityId;

                public EntityIdUniqueIndex(UserModerationStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class TargetEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(UserModerationState row) => row.TargetEntityId;

                public TargetEntityIdIndex(UserModerationStateHandle table) : base(table) { }
            }

            public readonly TargetEntityIdIndex TargetEntityId;

            internal UserModerationStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                TargetEntityId = new(this);
            }

            protected override object GetPrimaryKey(UserModerationState row) => row.EntityId;
        }

        public readonly UserModerationStateHandle UserModerationState;
    }
}
