// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UserAuthenticationStateHandle : RemoteTableHandle<EventContext, UserAuthenticationState>
        {
            protected override string RemoteTableName => "user_authentication_state";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(UserAuthenticationState row) => row.Identity;

                public IdentityUniqueIndex(UserAuthenticationStateHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal UserAuthenticationStateHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(UserAuthenticationState row) => row.Identity;
        }

        public readonly UserAuthenticationStateHandle UserAuthenticationState;
    }
}
