// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class VaultStateHandle : RemoteTableHandle<EventContext, VaultState>
        {
            protected override string RemoteTableName => "vault_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(VaultState row) => row.EntityId;

                public EntityIdUniqueIndex(VaultStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal VaultStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(VaultState row) => row.EntityId;
        }

        public readonly VaultStateHandle VaultState;
    }
}
