// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WaystoneStateHandle : RemoteTableHandle<EventContext, WaystoneState>
        {
            protected override string RemoteTableName => "waystone_state";

            public sealed class BuildingEntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(WaystoneState row) => row.BuildingEntityId;

                public BuildingEntityIdUniqueIndex(WaystoneStateHandle table) : base(table) { }
            }

            public readonly BuildingEntityIdUniqueIndex BuildingEntityId;

            public sealed class ClaimEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(WaystoneState row) => row.ClaimEntityId;

                public ClaimEntityIdIndex(WaystoneStateHandle table) : base(table) { }
            }

            public readonly ClaimEntityIdIndex ClaimEntityId;

            internal WaystoneStateHandle(DbConnection conn) : base(conn)
            {
                BuildingEntityId = new(this);
                ClaimEntityId = new(this);
            }

            protected override object GetPrimaryKey(WaystoneState row) => row.BuildingEntityId;
        }

        public readonly WaystoneStateHandle WaystoneState;
    }
}
