// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WeaponDescHandle : RemoteTableHandle<EventContext, WeaponDesc>
        {
            protected override string RemoteTableName => "weapon_desc";

            public sealed class ItemIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(WeaponDesc row) => row.ItemId;

                public ItemIdUniqueIndex(WeaponDescHandle table) : base(table) { }
            }

            public readonly ItemIdUniqueIndex ItemId;

            internal WeaponDescHandle(DbConnection conn) : base(conn)
            {
                ItemId = new(this);
            }

            protected override object GetPrimaryKey(WeaponDesc row) => row.ItemId;
        }

        public readonly WeaponDescHandle WeaponDesc;
    }
}
