// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WeaponTypeDescHandle : RemoteTableHandle<EventContext, WeaponTypeDesc>
        {
            protected override string RemoteTableName => "weapon_type_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(WeaponTypeDesc row) => row.Id;

                public IdUniqueIndex(WeaponTypeDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal WeaponTypeDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(WeaponTypeDesc row) => row.Id;
        }

        public readonly WeaponTypeDescHandle WeaponTypeDesc;
    }
}
