// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.


#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraftRegion.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WorldRegionNameStateHandle : RemoteTableHandle<EventContext, WorldRegionNameState>
        {
            protected override string RemoteTableName => "world_region_name_state";

            public sealed class IdUniqueIndex : UniqueIndexBase<ushort>
            {
                protected override ushort GetKey(WorldRegionNameState row) => row.Id;

                public IdUniqueIndex(WorldRegionNameStateHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal WorldRegionNameStateHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(WorldRegionNameState row) => row.Id;
        }

        public readonly WorldRegionNameStateHandle WorldRegionNameState;
    }
}
